// 领域 5：座舱（60 题）
const COCKPIT_QUESTIONS = [
  { id: 501, chapter: 5, type: "single", question: "「智能座舱」的核心硬件是？", options: ["A. 座舱域控制器 + SoC 芯片", "B. 只有座椅", "C. 只有空调", "D. 只有音箱"], answer: "A", explanation: "智能座舱的核心硬件是座舱域控制器 + SoC 芯片，集中承载仪表、中控、娱乐等系统。" },
  { id: 502, chapter: 5, type: "single", question: "「座舱域控制器」的作用是？", options: ["A. 座舱中央算力平台，集成仪表/中控/娱乐/导航多系统", "B. 只做收音机", "C. 与算力无关", "D. 只做座椅调节"], answer: "A", explanation: "座舱域控制器是座舱中央算力平台，集成仪表、中控、娱乐、导航等多屏多系统。" },
  { id: 503, chapter: 5, type: "single", question: "「舱驾一体」指的是？", options: ["A. 座舱与智驾共用一套硬件/芯片，降本增效", "B. 座舱与发动机一体", "C. 座椅与方向盘一体", "D. 与硬件无关"], answer: "A", explanation: "舱驾一体指座舱与智驾共用一套硬件/芯片，降低成本、提升协同体验。" },
  { id: 504, chapter: 5, type: "single", question: "「舱泊一体」指的是？", options: ["A. 座舱与泊车共用算力", "B. 只做泊车", "C. 与座舱无关", "D. 只做导航"], answer: "A", explanation: "舱泊一体指座舱与自动泊车共用算力平台，是算力融合的常见形态。" },
  { id: 505, chapter: 5, type: "single", question: "座舱 SoC 芯片代差（8295→8775→8397）直接决定？", options: ["A. 座舱算力与体验上限", "B. 只决定外观", "C. 与体验无关", "D. 只决定颜色"], answer: "A", explanation: "座舱 SoC 芯片代差直接决定算力与体验上限，是座舱升级的核心驱动力。" },
  { id: 506, chapter: 5, type: "single", question: "高通 8397 新一代 AI 座舱芯片相对 8295 的算力提升是？", options: ["A. 4 倍以上", "B. 约 2 倍", "C. 基本持平", "D. 反而降低"], answer: "A", explanation: "高通 8397 AI 座舱芯片性能是主流 8295 的 4 倍以上，驱动下一轮座舱算力升级。" },
  { id: 507, chapter: 5, type: "single", question: "「HMI」在座舱中指？", options: ["A. 人机交互界面，含语音、触控、手势、多屏、AR-HUD", "B. 只做硬件", "C. 与交互无关", "D. 只做座椅"], answer: "A", explanation: "HMI（人机交互界面）涵盖语音、触控、手势、多屏、AR-HUD 等交互方式。" },
  { id: 508, chapter: 5, type: "single", question: "「AR-HUD」的核心价值是？", options: ["A. 把导航等信息投射到前挡风，减少视线转移，提升安全", "B. 只做装饰", "C. 与安全无关", "D. 只做娱乐"], answer: "A", explanation: "AR-HUD 把导航、车速等信息投射到前挡风，与真实道路叠加，减少视线转移，提升安全。" },
  { id: 509, chapter: 5, type: "single", question: "「DMS」在座舱中指？", options: ["A. 驾驶员监测系统，检测疲劳、分心", "B. 只做音乐", "C. 与安全无关", "D. 只做导航"], answer: "A", explanation: "DMS（驾驶员监测系统）检测驾驶员疲劳、分心，是座舱安全的关键功能。" },
  { id: 510, chapter: 5, type: "single", question: "「OMS」在座舱中指？", options: ["A. 乘员监测系统，检测车内乘员状态（如儿童遗留）", "B. 只做空调", "C. 与乘员无关", "D. 只做座椅"], answer: "A", explanation: "OMS（乘员监测系统）检测车内乘员状态，如儿童遗留提醒等，是座舱安全功能。" },
  { id: 511, chapter: 5, type: "single", question: "「车手互联」指的是？", options: ["A. 手机与车机互联（Carplay/HiCar/Carlink），延伸手机生态", "B. 只做蓝牙", "C. 与手机无关", "D. 只做导航"], answer: "A", explanation: "车手互联通过 Carplay/HiCar/Carlink 把手机生态延伸进车内，覆盖主流手机用户。" },
  { id: 512, chapter: 5, type: "single", question: "上汽通用座舱车手互联的目标是？", options: ["A. 覆盖 Carplay/HiCar/Carlink，做国内适应性最好的车手互联", "B. 只支持苹果", "C. 不互联", "D. 只支持华为"], answer: "A", explanation: "上汽通用车机引入 HiCar、Carlink，加上 Carplay，目标是「国内适应性最好的车手互联」。" },
  { id: 513, chapter: 5, type: "single", question: "「大模型上车」对座舱交互的改变是？", options: ["A. 语音助手从命令式进化为理解式多模态交互", "B. 与交互无关", "C. 只做音乐", "D. 没有改变"], answer: "A", explanation: "大模型（豆包/混元等）上车让语音助手从「命令式」进化为「理解式」多模态交互。" },
  { id: 514, chapter: 5, type: "single", question: "「OTA」在座舱中的核心价值是？", options: ["A. 硬件一次性交付，体验靠软件持续迭代升级", "B. 只更新地图", "C. 与升级无关", "D. 只更新音乐"], answer: "A", explanation: "OTA 让座舱体验靠软件持续迭代升级，硬件一次性交付，是座舱的生命力所在。" },
  { id: 515, chapter: 5, type: "single", question: "博世 XC 在智能座舱领域的定位是？", options: ["A. 做座舱域控制器赋能，不做座舱应用", "B. 做座舱应用（地图/音乐 App）", "C. 做手机系统", "D. 不涉足座舱"], answer: "A", explanation: "博世 XC 明确「不做座舱应用，做座舱域控制器赋能」，专注算力平台与软硬件整合。" },
  { id: 516, chapter: 5, type: "single", question: "博世 XC 智能座舱域控制器首次实现的重要突破是？", options: ["A. 座舱算力首次超过手机", "B. 只做屏幕", "C. 与算力无关", "D. 只做语音"], answer: "A", explanation: "XC 中国区团队开发的座舱域控制器首次让座舱算力超过手机，为跨域融合做准备。" },
  { id: 517, chapter: 5, type: "single", question: "座舱域控制器支持「多屏联动」的意义是？", options: ["A. 仪表、中控、副驾娱乐、HUD、后排等多屏协同", "B. 只做一块屏", "C. 与联动无关", "D. 只做娱乐"], answer: "A", explanation: "多屏联动支持仪表、中控、副驾娱乐、HUD、后排等多屏协同，最高可达 8 屏联动。" },
  { id: 518, chapter: 5, type: "single", question: "「50 英寸 AR-HUD」的亮点是？", options: ["A. 超大画幅增强现实显示，信息更直观", "B. 只做小屏", "C. 与显示无关", "D. 只做装饰"], answer: "A", explanation: "50 英寸 AR-HUD 提供超大画幅增强现实显示，导航等信息更直观，是座舱升级亮点。" },
  { id: 519, chapter: 5, type: "single", question: "「主动降噪」在座舱中的作用是？", options: ["A. 用反向声波降低车内噪声，提升静谧性", "B. 只做音乐", "C. 与降噪无关", "D. 只做音量"], answer: "A", explanation: "主动降噪用反向声波抵消车内噪声，提升静谧性与乘坐体验。" },
  { id: 520, chapter: 5, type: "single", question: "「人脸识别」在座舱中的典型应用是？", options: ["A. 身份识别、个性化配置、疲劳监测", "B. 只做拍照", "C. 与识别无关", "D. 只做娱乐"], answer: "A", explanation: "座舱人脸识别用于身份识别、个性化配置、疲劳监测等，但涉及生物识别需合规。" },
  { id: 521, chapter: 5, type: "single", question: "「多麦克风输入」在座舱语音中的作用是？", options: ["A. 分区拾音，识别不同座位乘客的指令", "B. 只做录音", "C. 与语音无关", "D. 只做音乐"], answer: "A", explanation: "多麦克风分区拾音，识别不同座位乘客的语音指令，提升语音交互体验。" },
  { id: 522, chapter: 5, type: "single", question: "「360 度环视」在座舱/泊车场景的作用是？", options: ["A. 全景影像辅助泊车与观察盲区", "B. 只做娱乐", "C. 与泊车无关", "D. 只做导航"], answer: "A", explanation: "360 度环视用多个摄像头拼接全景影像，辅助泊车和观察盲区，是座舱+泊车常用功能。" },
  { id: 523, chapter: 5, type: "single", question: "腾讯「智慧座舱 TAI」的典型能力是？", options: ["A. 车载微信、腾讯爱趣听、腾讯地图等车机生态", "B. 只做社交", "C. 与座舱无关", "D. 只做游戏"], answer: "A", explanation: "腾讯智慧座舱 TAI 提供车载微信、腾讯爱趣听、腾讯地图等车机生态，补齐座舱内容与服务。" },
  { id: 524, chapter: 5, type: "single", question: "「车载微信」的座舱价值是？", options: ["A. 把高频社交延伸到车内，语音收发消息不分散驾驶注意力", "B. 只做聊天", "C. 与座舱无关", "D. 只做朋友圈"], answer: "A", explanation: "车载微信把高频社交延伸到车内，通过语音收发消息，减少驾驶分心，是腾讯座舱生态的核心。" },
  { id: 525, chapter: 5, type: "single", question: "腾讯「混元大模型」在座舱中的作用是？", options: ["A. 多模态语音助手、场景化智能推荐", "B. 只做翻译", "C. 与座舱无关", "D. 只做写作"], answer: "A", explanation: "混元大模型提供多模态语音助手、场景化智能推荐，助力大模型上车。" },
  { id: 526, chapter: 5, type: "single", question: "「座舱服务 1 个月上车」说明腾讯云座舱方案的什么优势？", options: ["A. 标准化服务快速上车，加速迭代", "B. 上车很慢", "C. 与速度无关", "D. 只能定制"], answer: "A", explanation: "腾讯智能座舱云方案可实现标准服务 1 个月上车，帮助车企快速迭代座舱产品。" },
  { id: 527, chapter: 5, type: "single", question: "座舱「软件订阅/应用下载」商业模式的价值是？", options: ["A. 硬件之外创造持续性软件收入", "B. 无价值", "C. 与商业无关", "D. 只做一次性"], answer: "A", explanation: "座舱软件订阅、应用下载等模式在硬件之外创造持续性软件收入，是软件定义汽车的价值体现。" },
  { id: 528, chapter: 5, type: "single", question: "「软件定义汽车（SDV）」的核心是？", options: ["A. 软件主导功能与体验，硬件平台化", "B. 只做硬件", "C. 与软件无关", "D. 只做外观"], answer: "A", explanation: "软件定义汽车以软件主导功能与体验，硬件平台化，通过 OTA 持续进化。" },
  { id: 529, chapter: 5, type: "single", question: "「多操作系统集成」在座舱域控中的意义是？", options: ["A. 同时运行仪表、中控、娱乐等多个操作系统", "B. 只跑一个系统", "C. 与系统无关", "D. 只做 Linux"], answer: "A", explanation: "多操作系统集成让域控同时运行仪表（安全关键）、中控（信息娱乐）等多个系统，兼顾安全与体验。" },
  { id: 530, chapter: 5, type: "single", question: "「信息娱乐系统（IVI）」属于座舱的哪部分？", options: ["A. 座舱的信息娱乐部分（导航、音乐、视频）", "B. 只做座椅", "C. 与娱乐无关", "D. 只做空调"], answer: "A", explanation: "IVI（信息娱乐系统）是座舱的信息娱乐部分，含导航、音乐、视频等。" },
  { id: 531, chapter: 5, type: "single", question: "「数字仪表」属于座舱哪部分？", options: ["A. 座舱显示部分，展示车速、导航等关键信息", "B. 只做娱乐", "C. 与显示无关", "D. 只做装饰"], answer: "A", explanation: "数字仪表是座舱显示部分，展示车速、导航等关键信息，属安全相关显示。" },
  { id: 532, chapter: 5, type: "single", question: "座舱「芯片算力」与「手机算力」的对比变化说明？", options: ["A. 座舱算力正追赶并超过手机，车机体验不再落后", "B. 座舱永远落后手机", "C. 与算力无关", "D. 座舱不用芯片"], answer: "A", explanation: "座舱算力正追赶并超过手机（博世 XC 首次实现），车机体验不再因算力落后。" },
  { id: 533, chapter: 5, type: "single", question: "「车机导航」体验差的历史原因是？", options: ["A. 开发到量产周期长，量产时算力已过时", "B. 导航不好用", "C. 与周期无关", "D. 只做地图"], answer: "A", explanation: "车机产品开发到量产需 3-4 年，量产时算力已落后手机，导致导航体验差，域控前瞻设计可解决。" },
  { id: 534, chapter: 5, type: "single", question: "「驾驶员监控（DMS）」的合规要点是？", options: ["A. 涉及人脸等生物识别，需增强行车安全目的+充分必要性", "B. 无合规要求", "C. 可随意采集", "D. 与隐私无关"], answer: "A", explanation: "DMS 涉及人脸等生物识别特征，采集需增强行车安全目的和充分必要性，受合规约束。" },
  { id: 535, chapter: 5, type: "single", question: "「车内语音」数据的合规属性是？", options: ["A. 音频属敏感个人信息，需告知+单独同意", "B. 与个人信息无关", "C. 可随意处理", "D. 只做娱乐"], answer: "A", explanation: "车内语音是音频，属敏感个人信息，需告知+单独同意，且遵循车内处理、默认不收集原则。" },
  { id: 536, chapter: 5, type: "single", question: "「座舱数据」与「智驾数据」的合规关系是？", options: ["A. 都受汽车数据法规约束，需统一合规治理", "B. 座舱无合规要求", "C. 智驾无合规要求", "D. 完全无关"], answer: "A", explanation: "座舱数据（语音、人脸、位置）与智驾数据（车外视频、轨迹）都受汽车数据法规约束，需统一合规治理。" },
  { id: 537, chapter: 5, type: "single", question: "「车机生态」竞争的实质是？", options: ["A. 内容与服务的生态之争，谁的内容丰富谁占优", "B. 只比硬件", "C. 与生态无关", "D. 只比外观"], answer: "A", explanation: "车机生态竞争的实质是内容与服务生态之争，腾讯以内容生态（微信、音乐、地图）切入。" },
  { id: 538, chapter: 5, type: "single", question: "「座舱 OTA」推送的安全前提是？", options: ["A. 可靠的云端分发 + 安全校验 + 回滚机制", "B. 无前提", "C. 与安全无关", "D. 只做推送"], answer: "A", explanation: "座舱 OTA 推送需可靠的云端分发、安全校验、回滚机制，避免升级失败影响行车安全。" },
  { id: 539, chapter: 5, type: "single", question: "「座舱域控」与「智驾域控」融合（舱驾一体）的技术前提是？", options: ["A. 高算力芯片 + 软硬件隔离保证安全", "B. 无前提", "C. 与安全无关", "D. 只做合并"], answer: "A", explanation: "舱驾一体需高算力芯片 + 软硬件隔离，保证安全关键功能与娱乐功能互不干扰。" },
  { id: 540, chapter: 5, type: "single", question: "「座舱安全」与「功能安全」的关系是？", options: ["A. 仪表等安全关键显示需功能安全，娱乐部分要求低", "B. 无关系", "C. 娱乐也要功能安全", "D. 仪表不需安全"], answer: "A", explanation: "仪表等安全关键显示需功能安全（如 ISO 26262），娱乐部分要求低，需软硬件隔离。" },
  { id: 541, chapter: 5, type: "single", question: "「语音助手」从命令式到理解式的关键是？", options: ["A. 大模型的多模态理解与推理能力", "B. 只做关键词", "C. 与理解无关", "D. 只做录音"], answer: "A", explanation: "大模型的多模态理解与推理能力让语音助手从命令式进化为理解式交互。" },
  { id: 542, chapter: 5, type: "single", question: "「副驾娱乐屏」的合规考量是？", options: ["A. 避免影响驾驶员注意力，需安全设计", "B. 无考量", "C. 可任意播放", "D. 与安全无关"], answer: "A", explanation: "副驾娱乐屏需安全设计（如防窥、分屏），避免影响驾驶员注意力。" },
  { id: 543, chapter: 5, type: "single", question: "「座舱数据大集中」后的安全挑战是？", options: ["A. 数据来源广、流动频繁，敏感数据泄露难追溯", "B. 无挑战", "C. 与安全无关", "D. 只做存储"], answer: "A", explanation: "座舱数据大集中后面临来源广、流动频繁、敏感数据泄露难追溯等安全挑战。" },
  { id: 544, chapter: 5, type: "single", question: "腾讯云「数据安全中心」对座舱数据的价值是？", options: ["A. 分类分级、全量审计、无侵入脱敏，实现数据安全治理", "B. 只做备份", "C. 与安全无关", "D. 只做监控"], answer: "A", explanation: "数据安全中心提供分类分级、全量审计、无侵入脱敏，是座舱数据安全治理的核心能力。" },
  { id: 545, chapter: 5, type: "single", question: "「座舱个性化配置」依赖的数据是？", options: ["A. 用户偏好数据（座椅、温度、音乐等），需合规处理", "B. 无数据", "C. 与偏好无关", "D. 只做默认"], answer: "A", explanation: "座舱个性化依赖用户偏好数据（座椅、温度、音乐等），属个人信息，需合规处理。" },
  { id: 546, chapter: 5, type: "single", question: "「车机账号体系」的合规要点是？", options: ["A. 账号关联个人信息，需告知+同意+安全保障", "B. 无要点", "C. 与合规无关", "D. 只做登录"], answer: "A", explanation: "车机账号体系关联个人信息，需告知、同意、安全保障，是座舱数据合规的重要环节。" },
  { id: 547, chapter: 5, type: "single", question: "「座舱内容生态」与「云」的关系是？", options: ["A. 音乐/视频/地图等内容靠云端分发与更新", "B. 与云无关", "C. 只做本地", "D. 只做缓存"], answer: "A", explanation: "座舱音乐、视频、地图等内容靠云端分发与更新，云是座舱内容生态的基础设施。" },
  { id: 548, chapter: 5, type: "single", question: "「舱驾一体」对车企的成本价值是？", options: ["A. 共用芯片/硬件，降低 BOM 成本", "B. 成本更高", "C. 与成本无关", "D. 只做高端"], answer: "A", explanation: "舱驾一体共用芯片/硬件，降低 BOM 成本，是车企降本的重要方向。" },
  { id: 549, chapter: 5, type: "single", question: "「座舱芯片国产化」的趋势背景是？", options: ["A. 供应链自主可控 + 成本考量", "B. 无背景", "C. 与自主无关", "D. 只做进口"], answer: "A", explanation: "座舱芯片国产化源于供应链自主可控与成本考量，是行业趋势。" },
  { id: 550, chapter: 5, type: "single", question: "「AR-HUD」与「传统 HUD」的区别是？", options: ["A. AR-HUD 与真实道路叠加增强现实，传统只投影信息", "B. 两者一样", "C. 传统更强", "D. 与显示无关"], answer: "A", explanation: "AR-HUD 与真实道路叠加增强现实，传统 HUD 只简单投影信息，AR-HUD 更直观安全。" },
  { id: 551, chapter: 5, type: "single", question: "「座舱主动安全」功能（DMS/OMS）的价值是？", options: ["A. 预防疲劳驾驶、儿童遗留等安全事故", "B. 只做娱乐", "C. 与安全无关", "D. 只做舒适"], answer: "A", explanation: "DMS/OMS 主动安全功能预防疲劳驾驶、儿童遗留等事故，是座舱安全的重要组成。" },
  { id: 552, chapter: 5, type: "single", question: "「车机系统升级」与「手机系统升级」的本质差异是？", options: ["A. 车机需车规级安全验证，周期更长", "B. 两者一样", "C. 车机更简单", "D. 与验证无关"], answer: "A", explanation: "车机系统升级需车规级安全验证，周期更长，是车机迭代慢于手机的根因。" },
  { id: 553, chapter: 5, type: "single", question: "「座舱数据出境」的典型场景是？", options: ["A. 跨国车企把中国座舱数据传回境外总部分析", "B. 无场景", "C. 与出境无关", "D. 只做境内"], answer: "A", explanation: "跨国车企把中国座舱数据（语音、偏好等）传回境外分析，需出境合规评估。" },
  { id: 554, chapter: 5, type: "single", question: "「座舱语音数据」用于「算法训练」的合规前提是？", options: ["A. 脱敏/匿名化 + 用户同意", "B. 无前提", "C. 可随意使用", "D. 与训练无关"], answer: "A", explanation: "座舱语音数据用于算法训练需脱敏/匿名化 + 用户同意，否则违反个人信息保护。" },
  { id: 555, chapter: 5, type: "single", question: "「多屏联动」的技术难点是？", options: ["A. 多屏协同渲染与低延迟同步", "B. 无难点", "C. 只做一块", "D. 与渲染无关"], answer: "A", explanation: "多屏联动难点在于多屏协同渲染与低延迟同步，需要高算力域控支撑。" },
  { id: 556, chapter: 5, type: "single", question: "「座舱内容付费」的合规要点是？", options: ["A. 支付、账号、个人信息合规", "B. 无要点", "C. 与合规无关", "D. 只做收费"], answer: "A", explanation: "座舱内容付费涉及支付、账号、个人信息等，需合规处理。" },
  { id: 557, chapter: 5, type: "single", question: "「腾讯爱趣听」的座舱定位是？", options: ["A. 车载音乐/音频内容服务", "B. 只做地图", "C. 与音频无关", "D. 只做社交"], answer: "A", explanation: "腾讯爱趣听是车载音乐/音频内容服务，是腾讯座舱内容生态的一部分。" },
  { id: 558, chapter: 5, type: "single", question: "「座舱 OTA」与「智驾 OTA」的关联是？", options: ["A. 可统一云端分发，但需分级安全验证", "B. 无关联", "C. 必须分开", "D. 只做座舱"], answer: "A", explanation: "座舱与智驾 OTA 可统一云端分发，但智驾涉及行车安全需更严格的分级验证。" },
  { id: 559, chapter: 5, type: "single", question: "「软件订阅」模式对「硬件平台化」的要求是？", options: ["A. 硬件预留算力与传感器，软件按需开启", "B. 无要求", "C. 硬件不可变", "D. 与订阅无关"], answer: "A", explanation: "软件订阅模式要求硬件平台化（预留算力与传感器），软件按需开启，实现持续变现。" },
  { id: 560, chapter: 5, type: "multiple", question: "智能座舱的关键组成包括？（多选）", options: ["A. 座舱域控制器与 SoC 芯片", "B. HMI（语音/多屏/AR-HUD）", "C. 车手互联（Carplay/HiCar/Carlink）", "D. 大模型上车与 OTA"], answer: ["A", "B", "C", "D"], explanation: "智能座舱由域控+SoC、HMI、车手互联、大模型与 OTA 等关键组成，共同构成体验。" },
];

export default COCKPIT_QUESTIONS;
